"""create migration

Revision ID: 359788f01e3b
Revises: 
Create Date: 2022-10-31 20:31:44.325067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359788f01e3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('URL_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original', sa.String(length=256), nullable=False),
    sa.Column('short', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('URL_map')
    # ### end Alembic commands ###
